Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2021-12, with the labels that each got.

#31 Add some list_items templates
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement, in-next-release

#34 Add custom card custom_card_saxel_fan
  custom_cards/custom_card_saxel_fan/custom_card_saxel_fan.yaml
  custom_cards/custom_card_saxel_fan/dark_theme.png
  custom_cards/custom_card_saxel_fan/light_theme.png
  custom_cards/custom_card_saxel_fan/readme.md
Labels: enhancement, in-next-release

#37 NL support and Typofix
  config/minimalist-templates/button_card_templates.yaml
  languages/NL.yaml
Labels: enhancement, in-next-release

#38 Add custom single icon chip card
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement, in-next-release

#39 Add custom card custom_card_schumijo_car
  custom_cards/custom_card_schumijo_car/README.md
  custom_cards/custom_card_schumijo_car/car.png
  custom_cards/custom_card_schumijo_car/custom_card_schumijo_car.yaml
  custom_cards/custom_card_schumijo_car/languages/EN.yaml
  custom_cards/custom_card_schumijo_car/languages/FR.yaml
Labels: enhancement, in-next-release

#46 Round temperature when the temperature has decimal points
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#50 Add Alarm Chip to availabe templates
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#53 Create SE.yaml
  custom_cards/custom_card_paddy_welcome/languages/SE.yaml
Labels: enhancement

#66 Vertical buttons custom state
  config/minimalist-templates/button_card_templates.yaml
  config/themes/minimalist-desktop/minimalist-desktop.yaml
  config/themes/minimalist-mobile/minimalist-mobile.yaml
Labels: enhancement

#72 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#74 Add yaml linter and pre-commit hook to GitHub actions
  .github/release-drafter.yml
  .github/workflows/format-code.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  .yamllint
  CHANGELOG.md
  README.md
  config/minimalist-templates/EN.yaml
  config/minimalist-templates/button_card_templates.yaml
  config/themes/minimalist-desktop/minimalist-desktop.yaml
  config/themes/minimalist-mobile/minimalist-mobile.yaml
  custom_cards/_custom_card_playstation/custom_card_playstation.yaml
  custom_cards/_custom_card_playstation/readme.md
  custom_cards/_custom_card_qubino/custom_card_qubino.yaml
  custom_cards/_custom_card_qubino/readme.md
  custom_cards/_custom_card_thermostat/custom_card_thermostat.yaml
  custom_cards/_custom_card_thermostat/readme.md
  custom_cards/_custom_card_water_heater/custom_card_water_heater.yaml
  custom_cards/_custom_card_water_heater/readme.md
  custom_cards/custom_card_nas/custom_card_nas.yaml
  custom_cards/custom_card_nas/readme.md
  custom_cards/custom_card_paddy_dwd_pollen/custom_card_paddy_dwd_pollen.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/DE.yaml
  custom_cards/custom_card_paddy_dwd_pollen/readme.md
  custom_cards/custom_card_paddy_waste_collection/custom_card_paddy_waste_collection.yaml
  custom_cards/custom_card_paddy_waste_collection/readme.md
  custom_cards/custom_card_paddy_welcome/custom_card_paddy_welcome.yaml
  custom_cards/custom_card_paddy_welcome/languages/DE.yaml
  custom_cards/custom_card_paddy_welcome/languages/EN.yaml
  custom_cards/custom_card_paddy_welcome/languages/FR.yaml
  custom_cards/custom_card_paddy_welcome/languages/SE.yaml
  custom_cards/custom_card_paddy_welcome/readme.md
  custom_cards/custom_card_saxel_fan/custom_card_saxel_fan.yaml
  custom_cards/custom_card_schumijo_car/README.md
  custom_cards/custom_card_schumijo_car/custom_card_schumijo_car.yaml
  custom_cards/custom_card_schumijo_car/languages/EN.yaml
  custom_cards/custom_card_schumijo_car/languages/FR.yaml
  custom_cards/custom_card_schumijo_flower/README.md
  custom_cards/custom_card_schumijo_flower/custom_card_schumijo_flower.yaml
  custom_cards/custom_card_schumijo_flower/languages/DE.yaml
  custom_cards/custom_card_schumijo_flower/languages/EN.yaml
  custom_cards/custom_card_schumijo_flower/languages/FR.yaml
  custom_cards/custom_card_tpx01_aircondition/custom_card_tpx01_aircondition.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/DE.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/EN.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/FR.yaml
  custom_cards/custom_card_tpx01_aircondition/readme.md
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/FR.yaml
  languages/NL.yaml
Labels: enhancement, review wanted

#78 Add unit on chip
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#76 Flower card language error
  custom_cards/custom_card_schumijo_flower/languages/DE.yaml
  custom_cards/custom_card_schumijo_flower/languages/EN.yaml
  custom_cards/custom_card_schumijo_flower/languages/FR.yaml
Labels: bugfix

#87 Fix custom zones on person card
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#90 Create SE.yaml
  languages/SE.yaml
Labels: translation

#84 Rework thermostat card to new templates
  config/minimalist-templates/EN.yaml
  config/minimalist-templates/button_card_templates.yaml
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/FR.yaml
  languages/NL.yaml
Labels: enhancement

#91 Fix german translation an clean some code
  .pre-commit-config.yaml
  config/minimalist-templates/button_card_templates.yaml
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/FR.yaml
Labels: translation

#80 More-info function light card and Custom auto-color light cards
  custom_cards/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/readme.md
  custom_cards/custom_card_light_icon_info/card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/readme.md
Labels: feature

#89 improved "card_battery" card
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#92 Introduce padding with card-mod-view-yaml
  config/themes/minimalist-desktop/minimalist-desktop.yaml
  config/themes/minimalist-mobile/minimalist-mobile.yaml
Labels: enhancement

#93 Add Spanish translations
  languages/ES.yaml
Labels: translation

#95 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#99 Make guest counter optional on chip_presence_detection
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#102 Set opacity-bg to 0.1 in light themes
  config/themes/minimalist-desktop/minimalist-desktop.yaml
  config/themes/minimalist-mobile/minimalist-mobile.yaml
Labels: bugfix

#103 Fix guest presence counter
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#112 Revert Set opacity-bg to 0.1
  .github/workflows/format-code.yml
  config/themes/minimalist-desktop/minimalist-desktop.yaml
  config/themes/minimalist-mobile/minimalist-mobile.yaml
Labels: bugfix

#113 Fix non colored chips on edge and chrome
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#124 IT Language for Welcome card.yaml
  custom_cards/custom_card_paddy_welcome/languages/IT.yaml
  custom_cards/custom_card_schumijo_car/languages/IT.yaml
  languages/IT.yaml
Labels: translation

#114 Make card_person zones optional and more robust
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#121 Custom-card "Device Tracker (Online or Offline ?)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  custom_cards/custom_card_vncntdev_device_tracer/preview.jpg
  custom_cards/custom_card_vncntdev_device_tracer/readme.md
  custom_cards/custom_card_vncntdev_device_tracer/vncntdev_card_device_tracer.yaml
Labels: feature

#127 Custom Input Number Card
  custom_cards/custom_card_input_number/card_input_number.yaml
  custom_cards/custom_card_input_number/readme.md
  screenshots/card_input_number.png
Labels: feature

#133 Added wifi signal card
  custom_cards/custom_card_mpse_wifisignal/custom_card_mpse_wifisignal.yaml
  custom_cards/custom_card_mpse_wifisignal/custom_wifisignal.png
  custom_cards/custom_card_mpse_wifisignal/readme.md
Labels: feature

#135 Restructure images in custom cards folder + fix broken links
  custom_cards/_custom_card_playstation/readme.md
  custom_cards/_custom_card_thermostat/readme.md
  custom_cards/custom_card_schumijo_car/README.md
  custom_cards/custom_card_schumijo_flower/README.md
  screenshots/car.png
  screenshots/flower.png
Labels: documentation

#116 Additional custom light card
  custom_cards/custom_card_light_colorpick/card_light_colorpick.yaml
  custom_cards/custom_card_light_colorpick/readme.md
Labels: feature

#140 New release light cards
  custom_cards/custom_card_light_color/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/custom_card_light_color/readme.md
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/dark.png
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/dark_horizontal.png
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/dark_slider.png
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/light.png
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/light_horizontal.png
  custom_cards/custom_card_light_color/custom_card_light_color/screenshots/light_slider.png
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/readme.md
Labels: enhancement, bugfix

#142 Fix lowercase readme files
  CHANGELOG.md
  custom_cards/custom_card_light_color/README.md
  custom_cards/custom_card_light_color/custom_card_light_color/README.md
  custom_cards/custom_card_light_colorpick/README.md
  custom_cards/custom_card_light_icon_info/README.md
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/README.md
  custom_cards/custom_card_paddy_welcome/README.md
Labels: documentation

#145 Automatically detect lowercase readme.md files
  .github/workflows/format-code.yml
  .pre-commit-config.yaml
  .pre-commit-search-and-replace.yaml
Labels: enhancement

#144 Hotfix: Fix folder structure for basbruss light cards
  custom_cards/custom_card_light_color/README.md
  custom_cards/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/screenshots/dark.png
  custom_cards/custom_card_light_color/screenshots/dark_horizontal.png
  custom_cards/custom_card_light_color/screenshots/dark_slider.png
  custom_cards/custom_card_light_color/screenshots/light.png
  custom_cards/custom_card_light_color/screenshots/light_horizontal.png
  custom_cards/custom_card_light_color/screenshots/light_slider.png
  custom_cards/custom_card_light_icon_info/README.md
  custom_cards/custom_card_light_icon_info/card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/card_light_icon_info.yaml
Labels: bugfix

#150 Hotfix for folder structure on basbruss light cards
  .github/workflows/format-code.yml
  .pre-commit-config.yaml
  .pre-commit-search-and-replace.yaml
  CHANGELOG.md
  custom_cards/custom_card_light_color/README.md
  custom_cards/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/custom_card_light_color/card_light_color.yaml
  custom_cards/custom_card_light_color/readme.md
  custom_cards/custom_card_light_color/screenshots/dark.png
  custom_cards/custom_card_light_color/screenshots/dark_horizontal.png
  custom_cards/custom_card_light_color/screenshots/dark_slider.png
  custom_cards/custom_card_light_color/screenshots/light.png
  custom_cards/custom_card_light_color/screenshots/light_horizontal.png
  custom_cards/custom_card_light_color/screenshots/light_slider.png
  custom_cards/custom_card_light_colorpick/README.md
  custom_cards/custom_card_light_icon_info/README.md
  custom_cards/custom_card_light_icon_info/card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/custom_card_light_icon_info/readme.md
  custom_cards/custom_card_paddy_welcome/README.md
Labels: bugfix

#132 Implementation of popup cards
  README.md
  README_popups.md
  config/minimalist-templates/EN.yaml
  config/minimalist-templates/popups_templates.yaml
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/ES.yaml
  languages/FR.yaml
  languages/IT.yaml
  languages/NL.yaml
  languages/SE.yaml
  screenshots/popup_light_phone.png
  screenshots/popup_light_tablet.png
  screenshots/popup_power_phone.png
  screenshots/popup_power_tablet.png
Labels: WIP, feature

#159 Add discord channel badge
  README.md
Labels: documentation

#160 Add discord channel badge
  README.md
Labels: documentation

#162 Use new slider from AnthonMS for popup card
  README.md
  config/minimalist-templates/popups_templates.yaml
Labels: bugfix

#169 Update README_popups.md
  README_popups.md
Labels: documentation

#163 Add Polish translations for cards
  custom_cards/custom_card_httpedo13_thermostat/languages/PL.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/PL.yaml
  custom_cards/custom_card_paddy_welcome/languages/PL.yaml
  custom_cards/custom_card_schumijo_car/languages/PL.yaml
  custom_cards/custom_card_schumijo_flower/languages/PL.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/PL.yaml
  languages/PL.yaml
Labels: translation

#176 Portuguese Translation
  custom_cards/custom_card_httpedo13_thermostat/languages/PT.yaml
  custom_cards/custom_card_paddy_welcome/languages/PT.yaml
  custom_cards/custom_card_schumijo_car/languages/PT.yaml
  custom_cards/custom_card_schumijo_flower/languages/PT.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/PT.yaml
  languages/PT.yaml
Labels: translation

#155 Update card_light_icon_info.yaml
  custom_cards/custom_card_light_icon_info/card_light_icon_info.yaml
Labels: bugfix

#156 Fix custom_card_saxel blue style card
  custom_cards/custom_card_saxel_fan/custom_card_saxel_fan.yaml
Labels: bugfix

#153 Fix battery_card icon color when state is unavailable
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#146 fix Card "card_media_player_with_controls" (missing variable "ulm_card_media_player_with_controls_entity")
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#154 New custom cards and update of existing ones
  config/minimalist-templates/button_card_templates.yaml
  custom_cards/custom_card_mpse_dualgraph/custom_card_mpse_dual_graph.yaml
  custom_cards/custom_card_mpse_dualgraph/custom_dual_graph.png
  custom_cards/custom_card_mpse_dualgraph/readme.md
  custom_cards/custom_card_mpse_gauge/custom_card_mpse_gauge.yaml
  custom_cards/custom_card_mpse_gauge/custom_gauge.png
  custom_cards/custom_card_mpse_gauge/readme.md
  custom_cards/custom_card_mpse_printer/custom_card_mpse_printer.yaml
  custom_cards/custom_card_mpse_printer/readme.md
  custom_cards/custom_card_mpse_thermostat/custom_card_mpse_thermostat.yaml
  custom_cards/custom_card_mpse_thermostat/custom_thermostat.png
  custom_cards/custom_card_mpse_thermostat/readme.md
  custom_cards/custom_card_mpse_wifisignal/custom_card_mpse_wifisignal.yaml
  custom_cards/custom_card_mpse_wifisignal/readme.md
Labels: feature

#149 Update button_card_templates.yaml
  config/minimalist-templates/button_card_templates.yaml
Labels: enhancement

#170 armed_away state for alarm chip
  config/minimalist-templates/EN.yaml
  config/minimalist-templates/button_card_templates.yaml
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/ES.yaml
  languages/FR.yaml
  languages/IT.yaml
  languages/NL.yaml
  languages/SE.yaml
Labels: enhancement
