Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-02, with the labels that each got.

#372 Feature: my enedis custom_chip
  custom_cards/custom_chip_myenedis/README.md
  custom_cards/custom_chip_myenedis/custom_chip_myenedis.yaml
  docs/assets/img/ulm_chips/chip_myenedis_all.png
  docs/assets/img/ulm_chips/chip_myenedis_hp_hc.png
Labels: :bulb: feature

#375 Correct slider when unavailable
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
Labels: :bug: bug

#125 Initial attempt at creating the room card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_room.yaml
  docs/assets/img/room-card.png
  docs/usage/cards/card_room.md
Labels: :bulb: feature

#378 Create custom_card_irmajavi_entities
  custom_cards/custom_card_irmajavi_entities/README.md
  custom_cards/custom_card_irmajavi_entities/custom_card_irmajavi_entities.yaml
Labels: :bulb: feature

#338 Add welcome_card for auto-generated dashboard
  custom_components/ui_lovelace_minimalist/lovelace/translations/DA.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/DE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/EN.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/FR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/IT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ui-lovelace.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_weather_date.yaml
  docs/assets/img/ulm_cards/card_welcome_scenes.png
  docs/usage/cards/card_welcome_scenes.md
Labels: :bulb: feature

#379 Custom card for Speedtest.net Integration
  custom_cards/custom_card_irmajavi_speedtest/README.md
  custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml
  custom_cards/custom_card_irmajavi_weather/README.md
  custom_cards/custom_card_irmajavi_weather/custom_card_irmajavi_weather.yaml
  docs/assets/img/screenshot_irmajavi_entities_card.jpg
  docs/assets/img/screenshot_irmajavi_speedtest_card.jpg
  docs/assets/img/screenshot_irmajavi_weather_card.jpg
Labels: :bulb: feature

#363 All in one card for thermostat + popup
  custom_components/ui_lovelace_minimalist/lovelace/translations/DA.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/DE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/EN.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/FR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/IT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/cards.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_aircondition.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  docs/assets/img/popup_thermostat_phone.png
  docs/assets/img/ulm_cards/card_thermostat.png
  docs/assets/img/ulm_cards/card_thermostat_with_controls.png
  docs/assets/img/ulm_cards/card_thermostat_with_hvac_and_color.png
  docs/usage/cards/card_thermostat.md
  docs/usage/popups/popup_aircondition.md
  docs/usage/popups/popup_thermostat.md
Labels: :memo: documentation, :sparkles: enhancement, :bulb: feature

#365 Add some predefined color templates to the ui
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/blue_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/blue_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/blue_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/green_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/green_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/green_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/grey_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/grey_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/grey_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/pink_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/pink_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/pink_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/red_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/red_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/red_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/violet_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/violet_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/violet_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/yellow_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/yellow_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/yellow_on.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/yellow_slider.yaml
Labels: :sparkles: enhancement

#348 Add Usage Layout and removed custom-repo from hacs docs
  docs/assets/img/layout/chip_center.png
  docs/assets/img/layout/chip_left_right.png
  docs/assets/img/layout/chip_right.png
  docs/setup/download.md
  docs/usage/.pages
  docs/usage/layout/index.md
Labels: :memo: documentation

#383 Pre-release improvements card_welcome_scenes
  custom_components/ui_lovelace_minimalist/lovelace/ui-lovelace.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  docs/usage/cards/card_welcome_scenes.md
Labels: :sparkles: enhancement

#382 [custom_card_scenes] Implementation of nested variables
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_scenes/card_scenes.yaml
Labels: :sparkles: enhancement

#377 Allow use of label or icon color in some chips
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_mdi_icon_only.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_mdi_icon_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_navigate.yaml
  docs/usage/chips/chip_mdi_icon_only.md
  docs/usage/chips/chip_mdi_icon_state.md
  docs/usage/chips/chip_navigate.md
Labels: :bulb: feature

#387 Improve custom card documentation
  docs/assets/img/fork.png
  docs/assets/img/unix_line_endings.png
  docs/assets/img/upload.png
  docs/development/card_style_guide.md
  docs/development/custom_cards.md
  docs/setup/configuration.md
  docs/setup/custom_cards.md
  mkdocs.yml
Labels: :memo: documentation

#394 Update Polish translation
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
Labels: :speech_balloon: translation

#395 Custom Card Homeassistant updates
  custom_cards/custom_card_homeassistant_updates/custom_card_homeassistant_updates.yaml
  custom_cards/custom_card_homeassistant_updates/readme.md
  docs/assets/img/ulm_cards/card_homeassistant_updates.png
Labels: :bulb: feature

#385 Added minimalist-mobile-tapbar theme
  custom_components/ui_lovelace_minimalist/blueprints/set_theme.yaml
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
Labels: :bulb: feature

#398 Update card_cover_buttons.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_cover_buttons.yaml
Labels: :sparkles: enhancement

#401 Fixed Typo
  docs/setup/download.md
Labels: :memo: documentation

#399 Add card_vacuum
  custom_components/ui_lovelace_minimalist/lovelace/translations/DA.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/DE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/EN.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/FR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/IT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NO.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
  docs/assets/img/ulm_cards/card_vacuum_cleaning.png
  docs/assets/img/ulm_cards/card_vacuum_docked.png
  docs/assets/img/ulm_cards/card_vacuum_returning.png
  docs/usage/cards/card_vacuum.md
Labels: :bulb: feature

#404 Update icon color to red when active only
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :sparkles: enhancement

#389 Add Czech & Slovak translations.
  custom_components/ui_lovelace_minimalist/configure.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/CS.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SK.yaml
  custom_components/ui_lovelace_minimalist/translations/cs.json
  custom_components/ui_lovelace_minimalist/translations/sk.json
Labels: :speech_balloon: translation

#388 Show Geolocation as label
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml
  docs/usage/cards/card_person.md
Labels: :bulb: feature

#403 Added ulm_language variables to name template
  custom_cards/custom_card_homeassistant_updates/README.md
  custom_cards/custom_card_homeassistant_updates/custom_card_homeassistant_updates.yaml
Labels: :sparkles: enhancement

#402 Variables updated
  custom_components/ui_lovelace_minimalist/lovelace/translations/EN.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
Labels: :sparkles: enhancement

#408 Language adjustments
  custom_cards/custom_card_damix48_power_details/languages/en.yaml
  custom_cards/custom_card_damix48_power_details/languages/it.yaml
  custom_cards/custom_card_damix48_power_details/languages/pl.yaml
  custom_cards/custom_card_heat_pump/languages/en.yaml
  custom_cards/custom_card_heat_pump/languages/pl.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/en.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/es.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/pl.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/pt.yaml
  custom_cards/custom_card_imswel_person/languages/de.yaml
  custom_cards/custom_card_imswel_person/languages/en.yaml
  custom_cards/custom_card_imswel_person/languages/es.yaml
  custom_cards/custom_card_imswel_person/languages/fr.yaml
  custom_cards/custom_card_imswel_person/languages/it.yaml
  custom_cards/custom_card_imswel_person/languages/pl.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/de.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/en.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/es.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/pl.yaml
  custom_cards/custom_card_paddy_welcome/languages/en.yaml
  custom_cards/custom_card_paddy_welcome/languages/es.yaml
  custom_cards/custom_card_paddy_welcome/languages/it.yaml
  custom_cards/custom_card_paddy_welcome/languages/pl.yaml
  custom_cards/custom_card_paddy_welcome/languages/pt.yaml
  custom_cards/custom_card_schumijo_car/languages/de.yaml
  custom_cards/custom_card_schumijo_car/languages/en.yaml
  custom_cards/custom_card_schumijo_car/languages/es.yaml
  custom_cards/custom_card_schumijo_car/languages/fr.yaml
  custom_cards/custom_card_schumijo_car/languages/it.yaml
  custom_cards/custom_card_schumijo_car/languages/pl.yaml
  custom_cards/custom_card_schumijo_car/languages/pt.yaml
  custom_cards/custom_card_schumijo_flower/languages/de.yaml
  custom_cards/custom_card_schumijo_flower/languages/en.yaml
  custom_cards/custom_card_schumijo_flower/languages/es.yaml
  custom_cards/custom_card_schumijo_flower/languages/fr.yaml
  custom_cards/custom_card_schumijo_flower/languages/it.yaml
  custom_cards/custom_card_schumijo_flower/languages/pl.yaml
  custom_cards/custom_card_schumijo_flower/languages/pt.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/de.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/en.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/es.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/fr.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/pl.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/pt.yaml
  custom_components/ui_lovelace_minimalist/configure.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sv.yaml
Labels: :speech_balloon: translation

#412 Italian translations for settings page
  custom_components/ui_lovelace_minimalist/translations/it.json
Labels: :speech_balloon: translation

#410 Add armed_night alarm status to chip_alarm
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sv.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_alarm.yaml
Labels: :sparkles: enhancement

#419 card_room to use `unit_of_measurement` if present
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_room.yaml
Labels: :sparkles: enhancement

#418 update card_thermostat to use climate entity temperature step if present
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :sparkles: enhancement

#425 Moving image to correct folder for the docs.
  docs/assets/img/ulm_cards/room-card.png
Labels: :memo: documentation

#432 Updating docs/setup
  docs/setup/configuration.md
  docs/setup/custom_cards.md
  docs/setup/installation.md
Labels: :memo: documentation

#437 Replaced hard coded entity
  custom_cards/custom_card_input_datetime/card_input_datetime.yaml
Labels: :bug: bug

#448 fix typing error
  docs/setup/configuration.md
Labels: :memo: documentation

#447 custom_card_afvalophaling
  custom_cards/custom_card_afvalophaling/README.md
  custom_cards/custom_card_afvalophaling/card_afvalophaling.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  docs/assets/img/ulm_cards/custom_card_afvalophaling_1.png
  docs/assets/img/ulm_cards/custom_card_afvalophaling_2.png
Labels: :bulb: feature

#446 Custom card eraycetinay elapsed time
  custom_cards/custom_card_eraycetinay_elapsed_time/README.md
  custom_cards/custom_card_eraycetinay_elapsed_time/custom_card_eraycetinay_elapsed_time.yaml
  custom_cards/custom_card_eraycetinay_elapsed_time/languages/en.yaml
  custom_cards/custom_card_eraycetinay_elapsed_time/languages/tr.yaml
  docs/assets/img/custom_card_eraycetinay_elapsed_time.png
Labels: :bulb: feature

#422 change border-radius to ha-card-border-radius
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-desktop/minimalist-desktop.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile/minimalist-mobile.yaml
Labels: :sparkles: enhancement

#439 custom_card_eraycetinay_lock
  custom_cards/custom_card_eraycetinay_lock/README.md
  custom_cards/custom_card_eraycetinay_lock/custom_card_eraycetinay_lock.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/en.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/tr.yaml
  docs/assets/img/custom_card_eraycetinay_lock_locked.png
  docs/assets/img/custom_card_eraycetinay_lock_unlocked.png
Labels: :bulb: feature

#449 thermostat label off mode added
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :bug: bug

#421 added auto entities and simple-weather-card
  docs/setup/installation.md
Labels: :memo: documentation

#434 Card Media Player:
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :sparkles: enhancement

#450 Add logic to determine if climate entity is using Fahrenheit or Celsius
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :sparkles: enhancement

#455 custom_card_eraycetinay_elapsed_time - readme.md fixes
  custom_cards/custom_card_eraycetinay_elapsed_time/README.md
Labels: :memo: documentation

#433 Update Czech & Slovak translations.
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
Labels: :speech_balloon: translation

#460 Use variables instead of sensor values to set colors for Afvalophaling
  custom_cards/custom_card_afvalophaling/card_afvalophaling.yaml
Labels: :bug: bug

#461 Add tiny translation fix
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_playing.yaml
Labels: :speech_balloon: translation

#457 Hotfix border-radius
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-desktop/minimalist-desktop.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile/minimalist-mobile.yaml
Labels: :bug: bug

#458 Fix wrong template name in yellow_off template
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/yellow_off.yaml
Labels: :bug: bug

#409 Added tap_action to chip_icon_double_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_icon_double_state.yaml
  docs/usage/chips/chip_icon_double_state.md
Labels: :sparkles: enhancement

#464 Custom card device tracker
  custom_cards/custom_card_device_tracker/custom_card_device_tracker.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sv.yaml
  docs/assets/img/custom_card_device_tracker.png
  docs/usage/custom_cards/custom_card_device_tracker.md
Labels: :bulb: feature

#289 Improve media player render with diverse entity_picture
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player_art.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player_controls.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/card_media_player_art.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/card_media_player_controls.yaml
  docs/assets/img/ulm_cards/card_media_player.png
  docs/assets/img/ulm_cards/card_media_player_art.png
  docs/assets/img/ulm_cards/card_media_player_art_control.png
  docs/assets/img/ulm_cards/card_media_player_art_controls.png
  docs/assets/img/ulm_cards/card_media_player_control.png
  docs/assets/img/ulm_cards/card_media_player_controls.png
  docs/assets/img/ulm_cards/card_media_player_icon.png
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_media_player_art.md
  docs/usage/cards/card_media_player_controls.md
Labels: :sparkles: enhancement

#468 Update custom_cards.md
  docs/development/custom_cards.md
Labels: :memo: documentation

#473 Person chip
  custom_cards/custom_card_person_chip/README.md
  custom_cards/custom_card_person_chip/custom_card_person_chip.yaml
Labels: :bulb: feature

#443 [bugfix] Changed some Toolbar sizing and padding in Tapbar theme
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
Labels: :bug: bug

#465 Add usb charging option for card_battery
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
Labels: :sparkles: enhancement
