Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-01, with the labels that each got.

#181 Missing variables in new language files
  config/minimalist-templates/button_card_templates.yaml
  languages/PL.yaml
  languages/PT.yaml
Labels: translation

#184 Update ES.yaml
  languages/ES.yaml
Labels: translation

#183 Light Slider unavailable color
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#182 Update chips_icon_label to use base chips template
  config/minimalist-templates/button_card_templates.yaml
Labels: bugfix

#188 Removed show last change
  custom_cards/custom_card_input_number/readme.md
Labels: documentation

#186 Make state of person card translatable
  config/minimalist-templates/EN.yaml
  config/minimalist-templates/button_card_templates.yaml
  languages/DE.yaml
  languages/DE_capitalized.yaml
  languages/ES.yaml
  languages/FR.yaml
  languages/IT.yaml
  languages/NL.yaml
  languages/PL.yaml
  languages/PT.yaml
  languages/SE.yaml
Labels: enhancement, review wanted

#215 HACS: Remove duplicated pre commit hooks and rearange them
  .github/labels.yml
  .github/workflows/check-code-quality.yml
  .github/workflows/labeler.yml
  .pre-commit-config.yaml
Labels: :sparkles: enhancement

#216 Adopt Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/labels.yml
Labels: :sparkles: enhancement

#217 Release-Drafter: Change Icons ans label association
  .github/release-drafter.yml
Labels: :sparkles: enhancement

#206 Created ES translation in every custom card.
  custom_cards/custom_card_httpedo13_thermostat/languages/ES.yaml
  custom_cards/custom_card_paddy_dwd_pollen/languages/ES.yaml
  custom_cards/custom_card_paddy_welcome/languages/ES.yaml
  custom_cards/custom_card_schumijo_car/languages/ES.yaml
  custom_cards/custom_card_schumijo_flower/languages/ES.yaml
  custom_cards/custom_card_tpx01_aircondition/languages/ES.yaml
Labels: :speech_balloon: translation

#218 HACS: Move new ES translations to new folder
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_httpedo13_thermostat/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_paddy_dwd_pollen/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_paddy_welcome/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_schumijo_car/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_schumijo_flower/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_tpx01_aircondition/languages/ES.yaml
Labels: :speech_balloon: translation

#219 HACS: Add HACS Check github action
  .github/workflows/hacs-action.yml
Labels: :sparkles: enhancement

#220 HACS: Fix Jinja Yaml load
  .devcontainer/README.md
  custom_components/ui_lovelace_minimalist/process_yaml.py
Labels: :bug: bug

#214 Media Player popup
  README_popups.md
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/popups_templates.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-desktop.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile.yaml
  screenshots/popup_media_phone.png
  screenshots/popup_media_tablet.png
Labels: :bulb: feature

#212 Added weather card
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/button_card_templates.yaml
Labels: :bulb: feature

#222 HACS: Add hassfest validation
  .github/workflows/hacs-action.yml
  .github/workflows/hacs-validate.yml
Labels: :sparkles: enhancement

#223 HACS: Add IOT class to manifest
  .github/workflows/hacs-validate.yml
  custom_components/ui_lovelace_minimalist/manifest.json
Labels: :sparkles: enhancement

#221 Add unit of measurement in chip_power_consumption when price is not showed
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/button_card_templates.yaml
Labels: :sparkles: enhancement

#210 Added new features to graph card (bar, dual graph, time)
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/button_card_templates.yaml
Labels: :bulb: feature

#205 Make chip_alarm colours use theme variables
  config/minimalist-templates/button_card_templates.yaml
Labels: :sparkles: enhancement

#225 change alarm panel colors
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/button_card_templates.yaml
Labels: :sparkles: enhancement

#203 Custom Scenes Card
  custom_cards/custom_card_scenes/card_scenes.yaml
  custom_cards/custom_card_scenes/readme.md
  screenshots/card_scenes.png
Labels: :bulb: feature

#226 HACS: Move custom scenes card
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_scenes/card_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_scenes/readme.md
Labels: :sparkles: enhancement

#202 New sun card
  custom_cards/custom_card_httpedo13_sun/custom_card_httpedo13_sun.yaml
  custom_cards/custom_card_httpedo13_sun/readme.md
  screenshots/sun-card.png
Labels: :bulb: feature

#227 HACS: Adopt sun card to new folder strucuture
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_httpedo13_sun/custom_card_httpedo13_sun.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_httpedo13_sun/readme.md
Labels: :sparkles: enhancement

#200 media player reorder and cleanup
  custom_components/ui_lovelace_minimalist/lovelace/button-cards-templates/button_card_templates.yaml
Labels: :sparkles: enhancement

#194 device tracker v1.1.0
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_vncntdev_device_tracer/preview-WoL.jpg
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_vncntdev_device_tracer/readme.md
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_vncntdev_device_tracer/vncntdev_card_device_tracer.yaml
Labels: :sparkles: enhancement

#199 add chromecast card
  custom_cards/custom_card_chromecast/custom_card_chromecast.yaml
  custom_cards/custom_card_chromecast/readme.md
  screenshots/chromecast.png
Labels: :bulb: feature

#228 HACS: Adopt chromecast card to folder structure
  .github/labels.yml
  custom_cards/custom_card_chromecast/custom_card_chromecast.yaml
  custom_cards/custom_card_chromecast/readme.md
Labels: :sparkles: enhancement

#189 Add media player sonos card
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_media_player_sonos/custom_card_media_player_sonos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_media_player_sonos/readme.md
  custom_components/ui_lovelace_minimalist/lovelace/translations/EN.yaml
  screenshots/media_player_sonos.png
Labels: :bulb: feature

#232 HACS: Ignore HACS and Brand check for now
  .github/workflows/hacs-validate.yml
Labels: :sparkles: enhancement

#230 HACS: more rename Fixes
  .gitignore
  custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml
  custom_components/ui_lovelace_minimalist/manifest.json
  custom_components/ui_lovelace_minimalist/process_yaml.py
  hacs.json
  info.md
  setup.cfg
Labels: :sparkles: enhancement

#229 Add Power details custom-card
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/README.md
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/custom_card_damix48_power_details.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/custom_power_details.png
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/languages/EN.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/languages/IT.yaml
Labels: :bulb: feature

#234 Add italian to schumijo_flower
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_schumijo_flower/languages/IT.yaml
Labels: :speech_balloon: translation

#233 Custom Bar Card
  custom_cards/custom_card_bar_card/custom_card_bar_card.yaml
  custom_cards/custom_card_bar_card/readme.md
  custom_cards/custom_card_bar_card/screenshot_bar_card.png
Labels: :bulb: feature

#235 HACS: Move bar card due to new folder strucutre
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_bar_card/custom_card_bar_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_bar_card/readme.md
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_bar_card/screenshot_bar_card.png
Labels: :sparkles: enhancement

#236 HACS: Fix custom_cards dir
  custom_components/ui_lovelace_minimalist/process_yaml.py
Labels: :bug: bug

#243 Unify language file structure and impove de
  custom_components/ui_lovelace_minimalist/lovelace/translations/DE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/FR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/IT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
Labels: :speech_balloon: translation

#244 Add release workflow for manifest update
  .github/update_hacs_manifest.py
  .github/workflows/release.yml
Labels: :sparkles: enhancement

#247 Update Polish translation
  custom_components/ui_lovelace_minimalist/lovelace/custom_cards/custom_card_damix48_power_details/languages/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
Labels: :speech_balloon: translation

#209 Fix black and white weather icons when bold
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/chips.yaml
Labels: :bug: bug

#211 Replacement card for vertical_button + vertical_button_custom_state
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vertical_button.yaml
Labels: :sparkles: enhancement

#248 Create Minimalist UI Logo.sketch
  assets/logos/sketch/Minimalist UI Logo.sketch
Labels: :memo: documentation

#251 Fix Logo
  mkdocs.yml
Labels: :memo: documentation

#252 Documentation improvements
  .github/workflows/pages.yml
  README_DOCS.md
  docs/index.md
  docs/setup/configuration.md
  docs/setup/index.md
  docs/setup/install.md
  docs/style-guide.md
  docs/usage/cards/._example.md
  docs/usage/cards/img/example.png
  docs/usage/cards/index.md
  docs/usage/index.md
Labels: :memo: documentation

#249 HACS: fix custom card folder structure
  custom_cards/custom_card_bar_card/README.md
  custom_cards/custom_card_damix48_power_details/languages/PL.yaml
  custom_components/ui_lovelace_minimalist/process_yaml.py
Labels: :bug: bug

#253 New All In one light card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light_slider.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light_slider_collapse.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light_slider_horizontal.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/cards.yaml
  docs/assets/img/card_light_combi.png
  docs/usage/cards/light.md
Labels: :memo: documentation, :bulb: feature

#254 DRAFT: Add support for awesome-pages-plugin
  .github/workflows/pages.yml
  docs/assets/img/setup/hacs_integration_config.png
  docs/assets/stylesheets/extra.css
  docs/setup/configuration.md
  docs/setup/install.md
  docs/setup/installation.md
  docs/usage/cards/light.md
  mkdocs.yml
  requirements_dev.txt
Labels: :memo: documentation

#260 Add magiclink extensions
  mkdocs.yml
Labels: :memo: documentation

#257 Add example wiki files for every card chip and popup
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_alarm.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_icon_label.yaml
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_binary_sensor.md
  docs/usage/cards/card_binary_sensor_alert.md
  docs/usage/cards/card_cover_with_buttons.md
  docs/usage/cards/card_generic.md
  docs/usage/cards/card_generic_swap.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_input_boolean.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_media_player_with_control.md
  docs/usage/cards/card_media_player_with_controls.md
  docs/usage/cards/card_navigate.md
  docs/usage/cards/card_person.md
  docs/usage/cards/card_power_outlet.md
  docs/usage/cards/card_script.md
  docs/usage/cards/card_thermostat.md
  docs/usage/cards/card_title.md
  docs/usage/cards/card_vertical_button.md
  docs/usage/cards/card_weather.md
  docs/usage/chips/chip_alarm.md
  docs/usage/chips/chip_back.md
  docs/usage/chips/chip_icon_double_state.md
  docs/usage/chips/chip_icon_label.md
  docs/usage/chips/chip_icon_only.md
  docs/usage/chips/chip_icon_state.md
  docs/usage/chips/chip_mdi_icon_only.md
  docs/usage/chips/chip_mdi_icon_state.md
  docs/usage/chips/chip_navigate.md
  docs/usage/chips/chip_power_consumption.md
  docs/usage/chips/chip_presence_detection.md
  docs/usage/chips/chip_temperature.md
  docs/usage/popups/popup_aircondition.md
  docs/usage/popups/popup_light.md
  docs/usage/popups/popup_media_player.md
  docs/usage/popups/popup_power_outlet.md
Labels: :memo: documentation

#261 Add images
  docs/assets/img/card_battery.png
  docs/assets/img/card_binary_sensor.png
  docs/assets/img/card_binary_sensor_alert.png
  docs/assets/img/card_cover.png
  docs/assets/img/card_cover_buttons.png
  docs/assets/img/card_cover_slider.png
  docs/assets/img/card_cover_slider_horizontal.png
  docs/assets/img/card_fan.png
  docs/assets/img/card_fan_slider.png
  docs/assets/img/card_fan_slider_collapse.png
  docs/assets/img/card_fan_slider_horizontal.png
  docs/assets/img/card_generic.png
  docs/assets/img/card_generic_swap.png
  docs/assets/img/card_graph.png
  docs/assets/img/card_input_boolean.png
  docs/assets/img/card_light.png
  docs/assets/img/card_light_slider.png
  docs/assets/img/card_light_slider_collapse.png
  docs/assets/img/card_light_slider_horizontal.png
  docs/assets/img/card_media_player.png
  docs/assets/img/card_media_player_art.png
  docs/assets/img/card_media_player_art_control.png
  docs/assets/img/card_media_player_control.png
  docs/assets/img/card_navigate.png
  docs/assets/img/card_person.png
  docs/assets/img/card_power_outlet.png
  docs/assets/img/card_script.png
  docs/assets/img/card_thermostat.png
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_binary_sensor.md
  docs/usage/cards/card_binary_sensor_alert.md
  docs/usage/cards/card_cover_with_buttons.md
  docs/usage/cards/card_generic.md
  docs/usage/cards/card_generic_swap.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_input_boolean.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_media_player_with_control.md
  docs/usage/cards/card_media_player_with_controls.md
  docs/usage/cards/card_person.md
  docs/usage/cards/card_power_outlet.md
  docs/usage/cards/card_script.md
  docs/usage/cards/card_thermostat.md
Labels: :memo: documentation

#263 Update image documentation
  docs/assets/img/card_title.png
  docs/usage/cards/card_cover_with_buttons.md
  docs/usage/cards/card_light.md
  docs/usage/cards/card_media_player_with_control.md
  docs/usage/cards/card_media_player_with_controls.md
  docs/usage/cards/card_navigate.md
  docs/usage/cards/card_title.md
Labels: :memo: documentation

#259 Heat Pump Card
  custom_cards/custom_card_heat_pump/Heat_pump.PNG
  custom_cards/custom_card_heat_pump/README.md
  custom_cards/custom_card_heat_pump/custom_card_heat_pump.yaml
  custom_cards/custom_card_heat_pump/heat_pump.gif
  custom_cards/custom_card_heat_pump/languages/EN.yaml
Labels: :bulb: feature

#262 Update NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
Labels: :speech_balloon: translation

#265 HACS: Updated Devcontainer & fixed reload of custom_cards
  .devcontainer/README.md
  .devcontainer/configuration.yaml
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  .vscode/tasks.json
  custom_components/ui_lovelace_minimalist/process_yaml.py
  requirements_dev.txt
Labels: :bug: bug

#266 Update documentation with manual installation
  .github/workflows/release.yml
  docs/setup/configuration.md
  docs/setup/installation.md
Labels: :memo: documentation

#267 Add github workflow for automatic custom_cards docs
  .github/workflows/copy-custom-card-docs.yml
  docs/usage/custom_cards/._example.md
Labels: :memo: documentation

#271 Add card_battery description
  custom_cards/custom_card_thermostat/README.md
  custom_cards/custom_card_thermostat/custom_card_thermostat.yaml
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_binary_sensor.md
  docs/usage/cards/card_binary_sensor_alert.md
  docs/usage/cards/card_cover_with_buttons.md
  docs/usage/cards/card_generic.md
  docs/usage/cards/card_generic_swap.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_input_boolean.md
  docs/usage/cards/card_light.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_media_player_with_control.md
  docs/usage/cards/card_media_player_with_controls.md
  docs/usage/cards/card_navigate.md
  docs/usage/cards/card_person.md
  docs/usage/cards/card_power_outlet.md
  docs/usage/cards/card_script.md
  docs/usage/cards/card_thermostat.md
  docs/usage/cards/card_title.md
  docs/usage/cards/card_vertical_button.md
  docs/usage/cards/card_weather.md
  docs/usage/custom_cards/custom_card_thermostat.md
Labels: :memo: documentation

#273 Add Chip Docs
  docs/usage/chips/chip_alarm.md
  docs/usage/chips/chip_back.md
  docs/usage/chips/chip_icon_double_state.md
  docs/usage/chips/chip_icon_label.md
  docs/usage/chips/chip_icon_only.md
  docs/usage/chips/chip_icon_state.md
  docs/usage/chips/chip_mdi_icon_only.md
  docs/usage/chips/chip_mdi_icon_state.md
  docs/usage/chips/chip_navigate.md
  docs/usage/chips/chip_power_consumption.md
  docs/usage/chips/chip_presence_detection.md
  docs/usage/chips/chip_temperature.md
Labels: :memo: documentation

#280 Update ES.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ES.yaml
Labels: :speech_balloon: translation

#281 Change Layout of docs pages
  .github/workflows/pages.yml
  docs/assets/overrides/partials/footer.html
  docs/assets/stylesheets/extra.css
  docs/assets/stylesheets/monokai.css
  mkdocs.yml
Labels: :memo: documentation

#277 Bug fixes card_light and icon_more_info
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info.yaml
Labels: :bug: bug

#284 Auto dark mode box shadow custom_card_scenes
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_scenes/card_scenes.yaml
Labels: :sparkles: enhancement

#283 Update of card_light
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  docs/usage/cards/card_light.md
  docs/usage/popups/popup_light.md
Labels: :sparkles: enhancement

#288 Change dashboard location to external folder
  custom_components/ui_lovelace_minimalist/load_dashboard.py
  custom_components/ui_lovelace_minimalist/lovelace/ui-lovelace.yaml
  custom_components/ui_lovelace_minimalist/process_yaml.py
  docs/setup/configuration.md
  docs/setup/installation.md
Labels: :sparkles: enhancement

#296 Minor tweaks on configuration docs
  README.md
  docs/setup/configuration.md
Labels: :memo: documentation

#295 Add chip images
  docs/assets/img/ulm_chips/chip_alarm.png
  docs/assets/img/ulm_chips/chip_back.png
  docs/assets/img/ulm_chips/chip_icon_double_state.png
  docs/assets/img/ulm_chips/chip_icon_label.png
  docs/assets/img/ulm_chips/chip_icon_only.png
  docs/assets/img/ulm_chips/chip_icon_state.png
  docs/assets/img/ulm_chips/chip_mdi_icon_only.png
  docs/assets/img/ulm_chips/chip_mdi_icon_state.png
  docs/assets/img/ulm_chips/chip_navigate.png
  docs/assets/img/ulm_chips/chip_power_consumption.png
  docs/assets/img/ulm_chips/chip_presence_detection.png
  docs/assets/img/ulm_chips/chip_temperature.png
  docs/usage/chips/chip_alarm.md
  docs/usage/chips/chip_back.md
  docs/usage/chips/chip_icon_double_state.md
  docs/usage/chips/chip_icon_label.md
  docs/usage/chips/chip_icon_only.md
  docs/usage/chips/chip_icon_state.md
  docs/usage/chips/chip_mdi_icon_only.md
  docs/usage/chips/chip_mdi_icon_state.md
  docs/usage/chips/chip_navigate.md
  docs/usage/chips/chip_power_consumption.md
  docs/usage/chips/chip_presence_detection.md
  docs/usage/chips/chip_temperature.md
Labels: :memo: documentation

#292 Added danish language file
  custom_components/ui_lovelace_minimalist/lovelace/translations/DA.yaml
Labels: :speech_balloon: translation

#286 Create custom card input datetime
  custom_cards/custom_card_input_datetime/README.md
  custom_cards/custom_card_input_datetime/custom_card_input_datetime.yaml
Labels: :bulb: feature

#301 fix typo lable to label
  docs/assets/img/ulm_chips/chip_icon_label.png
Labels: :memo: documentation

#290 Fix simple weather card text alignment
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_weather.yaml
  docs/usage/cards/card_weather.md
Labels: :sparkles: enhancement

#306 Fix: Update media_player info template
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
Labels: :bug: bug

#308 Documentation impovements
  .github/workflows/contributors.yml
  README.md
  custom_cards/custom_card_httpedo13_thermostat/README.md
  custom_cards/custom_card_input_number/README.md
  custom_cards/custom_card_mpse_gauge/README.md
  docs/setup/configuration.md
  docs/setup/download.md
  docs/setup/installation.md
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_light.md
  docs/usage/chips/chip_temperature.md
  docs/usage/custom_cards/custom_card_mpse_gauge.md
Labels: :memo: documentation

#311 Add primary and secondary info vars to card_weather
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_weather.yaml
  docs/assets/img/ulm_cards/card_weather.png
  docs/usage/cards/card_weather.md
Labels: :sparkles: enhancement

#279 Add option to enable/disable side panel entry during Integration installation
  .devcontainer/README.md
  .devcontainer/configuration.yaml
  .devcontainer/post-create.sh
  .pre-commit-config.yaml
  custom_components/ui_lovelace_minimalist/base.py
  custom_components/ui_lovelace_minimalist/cards/button-card/button-card.js
  custom_components/ui_lovelace_minimalist/cards/light-entity-card/light-entity-card.js
  custom_components/ui_lovelace_minimalist/cards/lovelace-card-mod/card-mod.js
  custom_components/ui_lovelace_minimalist/cards/lovelace-card-mod/rollup.config.js
  custom_components/ui_lovelace_minimalist/cards/mini-graph-card/mini-graph-card-bundle.js
  custom_components/ui_lovelace_minimalist/cards/mini-media-player/mini-media-player-bundle.js
  custom_components/ui_lovelace_minimalist/cards/my-cards-slider-card/my-cards.js
  custom_components/ui_lovelace_minimalist/cards/simple-weather-card/simple-weather-card-bundle.js
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/.gitignore
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/package-lock.json
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/package.json
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/src/main.js
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/ulm-flexbox-card.js
  custom_components/ui_lovelace_minimalist/cards/ulm-flexbox-card/webpack.config.js
  custom_components/ui_lovelace_minimalist/config_flow.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/installation/global.yaml
  custom_components/ui_lovelace_minimalist/installation/rooms.yaml
  custom_components/ui_lovelace_minimalist/js/src/index.js
  custom_components/ui_lovelace_minimalist/js/ui-lovelace-minimalist.js
  custom_components/ui_lovelace_minimalist/load_dashboard.py
  custom_components/ui_lovelace_minimalist/load_plugins.py
  custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ui-lovelace.yaml
  custom_components/ui_lovelace_minimalist/process_yaml.py
  custom_components/ui_lovelace_minimalist/translations/en.json
  docs/setup/installation.md
Labels: :bulb: feature

#314 Update Theme Settings docs
  docs/setup/installation.md
Labels: :memo: documentation

#321 Add missing languages to config flow
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/process_yaml.py
Labels: :speech_balloon: translation

#322 SE: New translations & corrections
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
Labels: :speech_balloon: translation

#324 Clearify usage
  docs/usage/popups/popup_light.md
  docs/usage/popups/popup_media_player.md
  docs/usage/popups/popup_power_outlet.md
Labels: :memo: documentation

#325 added missing english translations
  README.md
  custom_cards/custom_card_paddy_dwd_pollen/languages/EN.yaml
  custom_cards/custom_card_paddy_welcome/languages/EN.yaml
  custom_cards/custom_card_paddy_welcome/languages/ES.yaml
Labels: :speech_balloon: translation

#328 Enable trigger to power_outlet card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_power_outlet.yaml
Labels: :sparkles: enhancement

#341 Version: 1.0.1 of custom_card_input_number
  custom_cards/custom_card_input_number/README.md
  custom_cards/custom_card_input_number/card_input_number.yaml
Labels: :sparkles: enhancement

#339 card_light: Use icon if it's set on the device
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
Labels: :sparkles: enhancement

#343 Adds norwegian translation.
  custom_components/ui_lovelace_minimalist/configure.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/NO.yaml
Labels: :speech_balloon: translation

#349 Correcting the titles in the doc(s)
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_binary_sensor.md
  docs/usage/cards/card_binary_sensor_alert.md
  docs/usage/cards/card_cover_with_buttons.md
  docs/usage/cards/card_generic.md
  docs/usage/cards/card_generic_swap.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_input_boolean.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_media_player_with_control.md
  docs/usage/cards/card_media_player_with_controls.md
  docs/usage/cards/card_navigate.md
  docs/usage/cards/card_person.md
  docs/usage/cards/card_power_outlet.md
  docs/usage/cards/card_script.md
  docs/usage/cards/card_thermostat.md
  docs/usage/cards/card_title.md
  docs/usage/cards/card_vertical_button.md
  docs/usage/cards/card_weather.md
  docs/usage/chips/chip_alarm.md
  docs/usage/chips/chip_back.md
  docs/usage/chips/chip_icon_double_state.md
  docs/usage/chips/chip_icon_label.md
  docs/usage/chips/chip_icon_only.md
  docs/usage/chips/chip_icon_state.md
  docs/usage/chips/chip_mdi_icon_only.md
  docs/usage/chips/chip_mdi_icon_state.md
  docs/usage/chips/chip_navigate.md
  docs/usage/chips/chip_power_consumption.md
  docs/usage/chips/chip_presence_detection.md
  docs/usage/chips/chip_temperature.md
Labels: :memo: documentation

#355 [custom_card_input_datetime] Update readme and add image and rename yaml file
  custom_cards/custom_card_input_datetime/README.md
  custom_cards/custom_card_input_datetime/card_input_datetime.yaml
  docs/assets/img/card_input_datetime.png
Labels: :sparkles: enhancement

#354 [custom_card_scenes] Fix readme and update image
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_scenes/card_scenes.yaml
  docs/assets/img/card_scenes.png
  docs/assets/img/ulm_cards/card_scenes.png
Labels: :sparkles: enhancement

#353 [custom_card_input_number] Update readme and add image
  custom_cards/custom_card_input_number/README.md
  docs/assets/img/card_input_number.png
Labels: :sparkles: enhancement

#359 Fix translations
  custom_components/ui_lovelace_minimalist/lovelace/translations/DE.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/FR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/IT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/NL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/PT.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/SE.yaml
Labels: :speech_balloon: translation

#361 Fix folder hirarchie on wiki
  docs/setup/configuration.md
  docs/setup/installation.md
Labels: :memo: documentation

#356 Updated docs for vert_butt
  docs/usage/cards/card_vertical_button.md
Labels: :memo: documentation

#362 Add support for xy mode
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
Labels: :sparkles: enhancement
