Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-05, with the labels that each got.

#633 Update Polish translation
  custom_cards/custom_card_yagrasdemonde_lights_count/languages/PL.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
Labels: :speech_balloon: translation

#646 Pollen card for Tomorrow.io integration
  custom_cards/custom_card_wsly_pollen/README.md
  custom_cards/custom_card_wsly_pollen/custom_card_wsly_pollen.yaml
  custom_cards/custom_card_wsly_pollen/languages/EN.yaml
  custom_cards/custom_card_wsly_pollen/languages/NL.yaml
  docs/assets/img/custom_card_wsly_pollen_dark.png
  docs/assets/img/custom_card_wsly_pollen_light.png
Labels: :bulb: feature

#637 Add french translation
  custom_cards/custom_card_damix48_power_details/languages/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
Labels: :speech_balloon: translation

#638 Fix custom_card_homeasssitant_updates
  custom_cards/custom_card_homeassistant_updates/README.md
  custom_cards/custom_card_homeassistant_updates/custom_card_homeassistant_updates.yaml
Labels: :bug: bug

#639 [Custom_card_esh_welcome] Fix missing entity on weather chip
  custom_cards/custom_card_esh_welcome/custom_card_esh_welcome.yaml
Labels: :sparkles: enhancement

#673 Fix unavailable status to card_battery
  custom_cards/custom_card_person_info/README.md
  custom_cards/custom_card_person_info/custom_card_person_info.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
  docs/assets/img/custom_card_person_info.png
  docs/assets/img/custom_card_person_info2.png
  docs/usage/custom_cards/custom_card_person_info.md
Labels: :bug: bug

#672 Fix Custom speedtest car
  custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml
Labels: :bug: bug

#667 Update Spanish translation
  custom_cards/custom_card_damix48_power_details/languages/es.yaml
  custom_cards/custom_card_eraycetinay_elapsed_time/languages/es.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/es.yaml
  custom_cards/custom_card_heat_pump/languages/es.yaml
  custom_cards/custom_card_paddy_welcome/languages/es.yaml
  custom_cards/custom_card_wsly_pollen/languages/ES.yaml
  custom_cards/custom_card_yagrasdemonde_lights_count/languages/ES.yaml
  custom_components/ui_lovelace_minimalist/translations/es.json
Labels: :speech_balloon: translation

#649 Custom card more power outlet
  custom_cards/custom_card_more_power_outlet/custom_card_more_power_outlet.yaml
  custom_cards/custom_card_more_power_outlet/readme.md
Labels: :bulb: feature

#689 Custom card camera
  custom_cards/custom_card_camera/README.md
  custom_cards/custom_card_camera/custom_card_camera.yaml
  docs/assets/img/screenshot_custom_camera1.png
  docs/assets/img/screenshot_custom_camera2.png
Labels: :bulb: feature

#691 Added a new Door Lock custom card
  custom_cards/custom_card_nik_door/README.md
  custom_cards/custom_card_nik_door/custom_card_nik_door.yaml
  docs/assets/img/custom_card_nik_door.png
Labels: :bulb: feature

#680 Adjust DE vacuum translation
  custom_cards/custom_card_damix48_power_details/languages/de.yaml
  custom_cards/custom_card_heat_pump/languages/de.yaml
  custom_cards/custom_card_heat_pump/languages/en.yaml
  custom_cards/custom_card_heat_pump/languages/pl.yaml
  custom_cards/custom_card_httpedo13_thermostat/custom_card_httpedo13_thermostat.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/en.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/pl.yaml
  custom_cards/custom_card_httpedo13_thermostat/languages/pt.yaml
  custom_cards/custom_card_paddy_welcome/custom_card_paddy_welcome.yaml
  custom_cards/custom_card_tpx01_aircondition/custom_card_tpx01_aircondition.yaml
  custom_cards/custom_card_wsly_pollen/languages/de.yaml
  custom_cards/custom_card_yagrasdemonde_lights_count/languages/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
Labels: :speech_balloon: translation

#695 Adjusted vacuum card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
  docs/usage/cards/card_vacuum.md
Labels: :sparkles: enhancement

#678 [card_welcome_scenes] update card and add new features
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  docs/testenv.code-workspace
  docs/usage/cards/card_welcome_scenes.md
Labels: :sparkles: enhancement

#694 Adjusted custom lock card
  custom_cards/custom_card_eraycetinay_lock/README.md
  custom_cards/custom_card_eraycetinay_lock/custom_card_eraycetinay_lock.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/de.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/en.yaml
Labels: :sparkles: enhancement

#699 Added Custom Card - NAS Summary Card
  custom_cards/custom_card_nik_door/README.md
  custom_cards/custom_card_nik_nas/README.md
  custom_cards/custom_card_nik_nas/custom_card_nik_nas.yaml
  docs/assets/img/custom_card_nik_nas_off.png
  docs/assets/img/custom_card_nik_nas_on.png
Labels: :bulb: feature

#697 Add counter support to input number custom card
  custom_cards/custom_card_input_number/card_input_number.yaml
Labels: :sparkles: enhancement

#698 Update README file for Input Number custom card
  custom_cards/custom_card_input_number/README.md
Labels: :memo: documentation

#703 Fix regression introduced by 75d4276 in translations
  custom_cards/custom_card_paddy_welcome/custom_card_paddy_welcome.yaml
Labels: :bug: bug
