Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-10, with the labels that each got.

#1037 [Chip Mdi Icon State] Use entity attribute for unit of measurement if available
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_mdi_icon_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  docs/usage/layout/index.md
Labels: :sparkles: enhancement

#1032 [popup_mediaplayer]Add auto-generated source selector
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_source.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_media_player_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_source.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_source_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_volume.yaml
  docs/usage/cards/card_media_player.md
Labels: :sparkles: enhancement

#1053 correct typo in variable
  custom_cards/custom_card_esh_room/README.md
Labels: :memo: documentation

#1046 [card_person] Exclude passive zones
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml
Labels: :bug: bug, :sparkles: enhancement

#1039 [popup_thermostat] Adapt for mixed casing cases in preset mode
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
Labels: :sparkles: enhancement

#1062 New weather card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_weather_ulm.yaml
  docs/assets/img/ulm_cards/card_weather_ulm.png
  docs/usage/cards/card_weather_ulm.md
Labels: :bulb: feature

#1067 Update es.json
  custom_components/ui_lovelace_minimalist/translations/es.json
  docs/setup/custom_cards.md
Labels: :speech_balloon: translation

#1061 Styling for popup selectors
  custom_components/ui_lovelace_minimalist/lovelace/translations/cn.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fi.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt-BR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ru.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sv.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/tr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_light_effect_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_light_palette_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_media_player_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_row_layout.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_effect.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_source.yaml
Labels: :sparkles: enhancement

#1063 Bugfixes
  custom_cards/custom_card_imswel_person/README.md
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/purple_no_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/purple_off.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/purple_on.yaml
Labels: :bug: bug

#1071 Fix #1069
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
Labels: :bug: bug
