Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-04, with the labels that each got.

#570 Fix april fools day inclusion
  custom_components/ui_lovelace_minimalist/cards/lovelace-card-mod/lovelace-card-mod.js
  scripts/update-cards.py
Labels: :bug: bug

#569 Portuguese translation for the person custom card
  custom_cards/custom_card_imswel_person/languages/pt.yaml
Labels: :speech_balloon: translation

#547 Improved DE localization
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
Labels: :speech_balloon: translation

#565 Add instructions to change the theme in settings
  docs/setup/installation.md
Labels: :memo: documentation

#555 card cover add collapse expand icon future
  custom_components/ui_lovelace_minimalist/cards/my-cards-slider-card/my-cards-slider-card.js
  custom_components/ui_lovelace_minimalist/cards/my-cards/my-cards.js
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  docs/usage/cards/card_cover.md
  scripts/update-cards.py
Labels: :sparkles: enhancement

#562 [Wiki] Fix typo's
  docs/development/docs_style_guide.md
  docs/setup/custom_cards.md
Labels: :memo: documentation

#563 [Wiki] adding FAQ and customizing pages
  docs/setup/custom_cards.md
  docs/setup/customizing.md
  docs/setup/download.md
  docs/troubleshooting/troubleshooting.md
  mkdocs.yml
Labels: :memo: documentation, :pray: help wanted

#567 Allow today or tomorrow collections to be optional for AfvalOphaling
  custom_cards/custom_card_afvalophaling/card_afvalophaling.yaml
Labels: :sparkles: enhancement

#543 card_media_player: Enhance icon, title and label
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  docs/usage/cards/card_media_player.md
Labels: :sparkles: enhancement

#577 Add variables for minSet and maxSet for brightness slider on light card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  docs/usage/cards/card_light.md
Labels: :sparkles: enhancement

#588 Fix pre-commit stuff + bump repo versions
  .pre-commit-config.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :game_die: dependencies

#594 My contribution, a card showing counter for lights on / covers open
  custom_cards/custom_card_yagrasdemonde_lights_count/README.md
  custom_cards/custom_card_yagrasdemonde_lights_count/custom_card_yagrasdemonde_lights_count.yaml
  custom_cards/custom_card_yagrasdemonde_lights_count/languages/EN.yaml
  custom_cards/custom_card_yagrasdemonde_lights_count/languages/FR.yaml
  docs/assets/img/screenshot_dark_count_lights.png
  docs/assets/img/screenshot_light_count_lights.png
Labels: :bulb: feature

#593 Custom Card Welcome Navigation
  custom_cards/custom_card_esh_welcome/README.md
  custom_cards/custom_card_esh_welcome/custom_card_esh_welcome.yaml
  docs/assets/img/custom_card_esh_welcome_dark.png
  docs/assets/img/custom_card_esh_welcome_light.png
Labels: :bulb: feature

#602 Update README.md
  custom_cards/custom_card_esh_welcome/README.md
Labels: :memo: documentation

#589 Update minimalist-ios-tapbar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-ios-tapbar/minimalist-ios-tapbar.yaml
Labels: :sparkles: enhancement

#592 Add generic collapsible option for media controls and volume slider
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  docs/usage/cards/card_media_player.md
Labels: :sparkles: enhancement

#600 Typo in custom_card_httpedo13_thermostat docs
  docs/usage/custom_cards/custom_card_httpedo13_thermostat.md
Labels: :memo: documentation

#585 Add default hold_action to custom_card_saxel_fan
  custom_cards/custom_card_saxel_fan/custom_card_saxel_fan.yaml
Labels: :sparkles: enhancement

#596 [card_thermostat] Handle high/low temperature, external climate fan, and color for cooling
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  docs/assets/img/ulm_cards/card_thermostat_with_high_low.png
  docs/usage/cards/card_thermostat.md
Labels: :sparkles: enhancement

#606 [chip_weather_date, card_welcome_scenes] Use system date in Chip
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_weather_date.yaml
  docs/usage/cards/card_welcome_scenes.md
Labels: :sparkles: enhancement

#610 Added Brazilian Portuguese translation
  custom_components/ui_lovelace_minimalist/configure.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt-BR.yaml
Labels: :speech_balloon: translation

#615 Fixed typo in the correct place
  custom_cards/custom_card_httpedo13_thermostat/README.md
Labels: :memo: documentation, :sparkles: enhancement

#621 Add garage and gate types to cover card
  custom_cards/custom_card_esh_welcome/custom_card_esh_welcome.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  docs/usage/cards/card_cover.md
Labels: :sparkles: enhancement

#623 [costum_card_elapsed_time] Add German language variables
  custom_cards/custom_card_eraycetinay_elapsed_time/languages/de.yaml
Labels: :speech_balloon: translation

#619 Russian language added.
  custom_components/ui_lovelace_minimalist/configure.py
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/ru.yaml
  custom_components/ui_lovelace_minimalist/translations/ru.json
Labels: :speech_balloon: translation

#628 custom_card_schumijo_car: Add popup Map to view car location
  custom_cards/custom_card_schumijo_car/custom_card_schumijo_car.yaml
Labels: :sparkles: enhancement

#629 Custom Room Card
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
  docs/assets/img/custom_card_esh_room_dark.png
  docs/assets/img/custom_card_esh_room_light.png
Labels: :sparkles: enhancement

#631 [card_thermostat] Correct typo in fan_only mode
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :bug: bug
