Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-07, with the labels that each got.

#777 Person Info card: Fix for undefined driving entity variable
  custom_cards/custom_card_person_info/custom_card_person_info.yaml
Labels: :bulb: custom feature

#780 Update custom_card_person_info - Include Locality
  custom_cards/custom_card_person_info/custom_card_person_info.yaml
Labels: :sparkles: custom enhancement

#811 card ristou person - fix doc + add new templates - v1.0.1
  custom_cards/custom_card_ristou_person/README.md
  custom_cards/custom_card_ristou_person/custom_card_ristou_person.yaml
Labels: :sparkles: custom enhancement

#816 Added missing default values for variables for custom card "custom_card_httpedo13_sun"
  custom_cards/custom_card_httpedo13_sun/custom_card_httpedo13_sun.yaml
Labels: :bug: bug, :sparkles: custom enhancement

#825 Updated README with correct information about release
  custom_cards/custom_card_nik_door/README.md
Labels: :memo: documentation

#833 [custom_card_scenes] Option to trigger automation
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_scenes/card_scenes.yaml
Labels: :sparkles: custom enhancement

#832 Updating danish translation
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/translations/da.json
Labels: :speech_balloon: translation

#830 Add custom_card_neekster_update
  custom_cards/custom_card_neekster_update/README.md
  custom_cards/custom_card_neekster_update/custom_card_neekster_update.yaml
  docs/assets/img/custom_card_neekster_update.png
Labels: :bulb: custom feature

#829 Make inside temp optional in chip_temperature
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_temperature.yaml
  docs/usage/chips/chip_temperature.md
Labels: :sparkles: enhancement

#827 Fix Icon tap action
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_graph.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic_swap.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_input_boolean.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
Labels: :bug: bug

#828 New more featureful custom_card_esh_room version (2.0.0)
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
  docs/assets/img/custom_card_esh_room_dark.png
  docs/assets/img/custom_card_esh_room_light.png
Labels: :sparkles: custom enhancement

#849 created se.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/sv.yaml
Labels: :speech_balloon: translation

#851 Create nl.yaml
  custom_cards/custom_card_schumijo_car/languages/nl.yaml
Labels: :speech_balloon: translation

#857 Add french translation to integration workflow
  custom_components/ui_lovelace_minimalist/translations/fr.json
Labels: :speech_balloon: translation

#859 Fix typo on docs
  docs/setup/custom_actions.md
Labels: :memo: documentation

#863 Update card_battery.md
  docs/usage/cards/card_battery.md
Labels: :memo: documentation

#865 Fix "edit page" links in documentation
  mkdocs.yml
Labels: :memo: documentation

#867 Make hvac_action optional on ulm_translation_hvac
  custom_components/ui_lovelace_minimalist/lovelace/translations/default.yaml
Labels: :sparkles: enhancement

#869 Show correct location in custom_card_person_chip
  custom_cards/custom_card_person_chip/custom_card_person_chip.yaml
Labels: :sparkles: custom enhancement

#872 Update es.yaml
  custom_cards/custom_card_damix48_power_details/README.md
  custom_cards/custom_card_damix48_power_details/custom_card_damix48_power_details.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/de.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/en.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/es.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/pl.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/tr.yaml
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
  custom_cards/custom_card_httpedo13_sun/custom_card_httpedo13_sun.yaml
  custom_cards/custom_card_input_datetime/card_input_datetime.yaml
  custom_cards/custom_card_input_number/card_input_number.yaml
  custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml
  custom_cards/custom_card_nas/README.md
  custom_cards/custom_card_neekster_update/README.md
  custom_cards/custom_card_neekster_update/custom_card_neekster_update.yaml
  custom_cards/custom_card_nik_door/README.md
  custom_cards/custom_card_nik_door/custom_card_nik_door.yaml
  custom_cards/custom_card_person_info/custom_card_person_info.yaml
  custom_cards/custom_card_ristou_person/README.md
  custom_cards/custom_card_ristou_person/custom_card_ristou_person.yaml
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_scenes/card_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/translations/da.json
  docs/assets/img/custom_card_esh_room_dark.png
  docs/assets/img/custom_card_esh_room_light.png
  docs/assets/img/custom_card_neekster_update.png
  docs/assets/img/custom_card_nik_door.png
  docs/index.md
  docs/usage/cards/card_battery.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_person.md
  docs/usage/custom_cards/custom_card_apexcharts.md
  docs/usage/custom_cards/custom_card_bar_card.md
  docs/usage/custom_cards/custom_card_damix48_power_details.md
  docs/usage/custom_cards/custom_card_eraycetinay_lock.md
  docs/usage/custom_cards/custom_card_nas.md
  docs/usage/custom_cards/custom_card_neekster_update.md
  docs/usage/custom_cards/custom_card_nik_door.md
  docs/usage/custom_cards/custom_card_nik_nas.md
  docs/usage/custom_cards/custom_card_nik_tablet.md
  docs/usage/custom_cards/custom_card_paddy_dwd_pollen.md
  docs/usage/custom_cards/custom_card_paddy_waste_collection.md
  docs/usage/custom_cards/custom_card_ristou_person.md
  docs/usage/custom_cards/custom_card_scenes.md
  docs/usage/custom_cards/custom_card_vncntdev_device_tracer.md
Labels: :speech_balloon: translation

#847 Card room. Code refactoring to fit framework structure.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_room.yaml
  docs/assets/img/ulm_cards/room-card.png
  docs/usage/cards/card_room.md
Labels: :sparkles: enhancement

#887 Fix typo in Device Tracker Custom-card doc
  docs/usage/custom_cards/custom_card_vncntdev_device_tracer.md
Labels: :memo: documentation

#892 Hide exclamation to solve #880
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_new.yaml
Labels: :bug: bug

#890 Added german language file for "custom_card_ristou_person"
  custom_cards/custom_card_ristou_person/languages/de.yaml
Labels: :speech_balloon: translation

#879 Fix text overflowing issue in custom card "room"
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
Labels: :sparkles: custom enhancement

#881 Custom Card "room" better text overflow and use of `ulm_actions_card`
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
Labels: :sparkles: custom enhancement

#907 Added cards for adaptive board
  custom_components/ui_lovelace_minimalist/base.py
  scripts/update-cards.py
Labels: :game_die: dependencies

#906 Add Codespell to pre-commit hook
  .codespell
  .codespellrc
  .devcontainer/README.md
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  custom_cards/custom_card_more_power_outlet/readme.md
  custom_cards/custom_card_mpse_gauge/README.md
  custom_cards/custom_card_mpse_printer/README.md
  custom_cards/custom_card_mpse_wifisignal/README.md
  custom_cards/custom_card_nik_tablet/README.md
  custom_cards/custom_card_paddy_welcome/README.md
  custom_cards/custom_card_ristou_person/README.md
  custom_cards/custom_card_saxel_fan/README.md
  custom_cards/custom_card_schumijo_car/README.md
  custom_components/ui_lovelace_minimalist/translations/en.json
  docs/assets/logos/Minimalist UI Logo.svg
  docs/development/card_style_guide.md
  docs/development/custom_cards.md
  docs/development/docs_style_guide.md
  docs/index.md
  docs/setup/adaptive_dash.md
  docs/setup/custom_actions.md
  docs/setup/customizing.md
  docs/setup/download.md
  docs/setup/installation.md
  docs/troubleshooting/troubleshooting.md
  docs/usage/cards/card_cover.md
  docs/usage/cards/card_graph.md
  docs/usage/cards/card_light.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_thermostat.md
  docs/usage/cards/card_title.md
  docs/usage/cards/card_vertical_button.md
  docs/usage/cards/card_weather.md
  docs/usage/chips/chip_back.md
  docs/usage/custom_cards/custom_card_mpse_gauge.md
  docs/usage/custom_cards/custom_card_mpse_printer.md
  docs/usage/custom_cards/custom_card_mpse_wifisignal.md
  docs/usage/custom_cards/custom_card_nik_tablet.md
  docs/usage/custom_cards/custom_card_paddy_welcome.md
  docs/usage/custom_cards/custom_card_ristou_person.md
  docs/usage/custom_cards/custom_card_saxel_fan.md
  docs/usage/custom_cards/custom_card_schumijo_car.md
Labels: :game_die: dependencies

#903 Community Card Selection Docs
  docs/setup/custom_cards.md
Labels: :memo: documentation

#878 Custom popups for cards that uses custom actions.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_graph.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic_swap.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_input_boolean.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/extended_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_new.yaml
Labels: :sparkles: enhancement

#898 Update card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :sparkles: enhancement
