Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-08, with the labels that each got.

#918 Fix name attribute in custom NAS card
  custom_cards/custom_card_nik_nas/custom_card_nik_nas.yaml
Labels: :bug: bug

#914 [card_media_player] added standby logic
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :sparkles: enhancement

#894 Add weather popup
  custom_components/ui_lovelace_minimalist/base.py
  custom_components/ui_lovelace_minimalist/lovelace/translations/cn.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fi.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt-BR.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ru.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sv.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/tr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_temperature.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_radar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_weather_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
  docs/assets/img/popup_weather_phone.png
  docs/assets/img/popup_weather_tablet.png
  docs/usage/popups/popup_weather.md
  scripts/update-cards.py
Labels: :bulb: feature

#919 Use entity variable for custom popups.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_chip_controls.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_volume.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_history.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_stats.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  docs/setup/custom_actions.md
Labels: :bulb: feature

#923 Small Fix before release
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_radar.yaml
Labels: :bug: bug

#929 Add call-service as action to custom actions.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/extended_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_new.yaml
  docs/setup/custom_actions.md
Labels: :sparkles: enhancement

#933 Add Text-overflow to Pills and Popup-Light
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
Labels: :sparkles: enhancement

#947 Update docs
  docs/assets/img/ulm_cards/card_scenes.png
  docs/setup/custom_cards.md
  docs/usage/cards/card_scenes.md
Labels: :memo: documentation

#939 Update to add customization options
  docs/usage/custom_cards/custom_card_esh_welcome.md
Labels: :memo: documentation

#964 Added docs for more_power_outlet
  docs/usage/custom_cards/custom_card_more_power_outlet.md
Labels: :memo: documentation

#961 Add dynamic background color option
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
Labels: :sparkles: custom enhancement

#962 lv.yaml
  custom_cards/custom_card_irmajavi_speedtest/languages/lv.yaml
Labels: :speech_balloon: translation

#963 Update and rename en.json to sl.json
  custom_components/ui_lovelace_minimalist/const.py
  custom_components/ui_lovelace_minimalist/translations/sl.json
  docs/assets/img/ulm_cards/card_scenes.png
  docs/setup/custom_cards.md
  docs/usage/cards/card_media_player.md
  docs/usage/cards/card_scenes.md
Labels: :speech_balloon: translation

#942 Fix number of forecast entities.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
  docs/setup/custom_actions.md
  docs/usage/popups/popup_weather.md
Labels: :sparkles: enhancement
