Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-09, with the labels that each got.

#973 Update custom_card_nas.md
  docs/usage/custom_cards/custom_card_nas.md
Labels: :memo: documentation

#948 Creation of popup thermostat which uses preset_mode instead of state.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  docs/usage/popups/popup_thermostat.md
Labels: :sparkles: enhancement

#971 Added NL translation
  custom_cards/custom_card_damix48_power_details/languages/nl.yaml
Labels: :speech_balloon: translation

#969 Fix 'custom_card_bar_card' bar border radius
  custom_cards/custom_card_bar_card/README.md
  custom_cards/custom_card_bar_card/custom_card_bar_card.yaml
Labels: :sparkles: custom enhancement

#972 Initial updates for browser_mod 2.0.0
  .devcontainer/post-create.sh
  custom_cards/custom_card_imswel_person/custom_card_imswel_person.yaml
  custom_cards/custom_card_schumijo_car/custom_card_schumijo_car.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_back.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_volume.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_history.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_stats.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
Labels: :game_die: dependencies

#974 Update popup power outlet
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic_swap.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_input_boolean.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  docs/usage/popups/popup_power_outlet.md
Labels: :sparkles: enhancement

#979 Update browser mod service
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_battery.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_generic_swap.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_input_boolean.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_power_outlet.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_chip_controls.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_volume.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_history.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_stats.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
Labels: :bug: bug

#980 Binary sensor alert card state
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_info_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_alert.yaml
  docs/usage/cards/card_binary_sensor_alert.md
Labels: :sparkles: enhancement

#988 Fix syntax error for name tap action
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
Labels: :bug: bug

#984 Fix incorrect description for ulm_card_graph_name in graph_card
  docs/usage/cards/card_graph.md
Labels: :memo: documentation

#991 Remove 2 zone limitation from person card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml
Labels: :sparkles: enhancement

#990 Removed background-blend-mode: "multiply" to fix Safari/iOS/iPadOS issues
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :bug: bug

#993 Add custom_card_drealine_roomview
  custom_cards/custom_card_drealine_roomview/README.md
  custom_cards/custom_card_drealine_roomview/custom_card_drealine_roomview.yaml
  docs/assets/img/custom_card_drealine_roomview_1.png
Labels: :bulb: custom feature

#1001 [Card_person] Add ETA and battery_sensor
  README.md
  custom_cards/custom_card_drealine_roomview/README.md
  custom_cards/custom_card_drealine_roomview/custom_card_drealine_roomview.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml
  docs/assets/img/custom_card_drealine_roomview_1.png
  docs/usage/cards/card_person.md
Labels: :sparkles: enhancement

#994 Fix alignments and added popup for cover card.
  custom_components/ui_lovelace_minimalist/lovelace/translations/default.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_new.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_cover_close.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_cover_open.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_cover_stop.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_cover.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  docs/assets/img/popup_cover.png
  docs/usage/popups/popup_cover.md
Labels: :sparkles: enhancement

#996 Add word-break to vertical popup buttons
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_history.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_stats.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
Labels: :sparkles: enhancement

#1002 Add group by capability for graph card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_graph.yaml
  docs/usage/cards/card_graph.md
Labels: :sparkles: enhancement

#1004 [card_esh_welcome] Add `ulm_custom_actions` to allow custom popups
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
Labels: :sparkles: custom enhancement

#1009 [card_vacuum] Fix bug card not displaying
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
Labels: :bug: bug

#1010 Fix thermostat popup card if no presets available
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
Labels: :bug: bug

#1011 Add Vacuum Popup
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_vacuum.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_vacuum_map.yaml
  docs/assets/img/popup_vacuum.PNG
  docs/assets/img/popup_vacuum_no_camera.PNG
  docs/usage/popups/popup_vacuum.md
Labels: :sparkles: enhancement

#1013 Fix overflow
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/icon_more_info_new.yaml
Labels: :bug: bug

#1021 Introduction of Last Changed for Cover Card
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  docs/usage/popups/popup_cover.md
Labels: :sparkles: enhancement
