Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2022-03, with the labels that each got.

#483 Fix pop-up mediaplayer
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
Labels: :bug: bug

#484 fix(card/thermostat): use hass configured system temperature unit
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
Labels: :sparkles: enhancement

#488 [card_welcome_scenes] Hotfix quoted booleans
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
Labels: :bug: bug

#489 Fix template error for legacy media player
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/card_media_player_art.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/card_media_player_controls.yaml
Labels: :bug: bug

#494 fix(dashboard): typo
  custom_components/ui_lovelace_minimalist/lovelace/ui-lovelace.yaml
Labels: :sparkles: enhancement

#503 Update Custom-cards titles
  custom_cards/custom_card_afvalophaling/README.md
  custom_cards/custom_card_bar_card/README.md
  custom_cards/custom_card_chromecast/README.md
  custom_cards/custom_card_damix48_power_details/README.md
  custom_cards/custom_card_device_tracker/README.md
  custom_cards/custom_card_eraycetinay_elapsed_time/README.md
  custom_cards/custom_card_eraycetinay_lock/README.md
  custom_cards/custom_card_heat_pump/README.md
  custom_cards/custom_card_homeassistant_updates/README.md
  custom_cards/custom_card_httpedo13_sun/README.md
  custom_cards/custom_card_httpedo13_thermostat/README.md
  custom_cards/custom_card_imswel_person/README.md
  custom_cards/custom_card_input_datetime/README.md
  custom_cards/custom_card_input_number/README.md
  custom_cards/custom_card_irmajavi_entities/README.md
  custom_cards/custom_card_irmajavi_speedtest/README.md
  custom_cards/custom_card_irmajavi_weather/README.md
  custom_cards/custom_card_light_colorpick/README.md
  custom_cards/custom_card_media_player_sonos/README.md
  custom_cards/custom_card_mpse_gauge/README.md
  custom_cards/custom_card_mpse_printer/README.md
  custom_cards/custom_card_mpse_thermostat/README.md
  custom_cards/custom_card_mpse_wifisignal/README.md
  custom_cards/custom_card_nas/README.md
  custom_cards/custom_card_paddy_dwd_pollen/README.md
  custom_cards/custom_card_paddy_waste_collection/README.md
  custom_cards/custom_card_paddy_welcome/README.md
  custom_cards/custom_card_playstation/README.md
  custom_cards/custom_card_qubino/README.md
  custom_cards/custom_card_saxel_fan/README.md
  custom_cards/custom_card_scenes/README.md
  custom_cards/custom_card_schumijo_car/README.md
  custom_cards/custom_card_schumijo_flower/README.md
  custom_cards/custom_card_tpx01_aircondition/README.md
  custom_cards/custom_card_vncntdev_device_tracer/README.md
  custom_cards/custom_card_water_heater/README.md
  custom_cards/custom_chip_myenedis/README.md
Labels: :memo: documentation

#501 Add a custom icon variable for the custom room script
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
  docs/usage/cards/card_vacuum.md
Labels: :sparkles: enhancement

#499 Add missing attributes to readme
  docs/usage/cards/card_input_boolean.md
  docs/usage/cards/card_vertical_button.md
Labels: :sparkles: enhancement

#507 [custom_card_afvalophaaling] Updated YAML code + fixes
  custom_cards/custom_card_afvalophaling/README.md
  custom_cards/custom_card_afvalophaling/card_afvalophaling.yaml
Labels: :bug: bug

#505 [card_light] Add "toggle" tap_action
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
Labels: :sparkles: enhancement

#512 Fix typo in README.md from custom_card_scenes
  custom_cards/custom_card_scenes/README.md
Labels: :memo: documentation

#523 Update card_welcome_scenes.md
  docs/usage/cards/card_welcome_scenes.md
Labels: :memo: documentation

#515 [card_media_player] Add volume slider
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_media_player.yaml
  docs/assets/img/ulm_cards/card_media_player_volume_slider.png
  docs/usage/cards/card_media_player.md
Labels: :sparkles: enhancement

#491 New AIO cover card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_cover_buttons.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/legacy_templates/cards.yaml
  docs/assets/img/ulm_cards/card_cover.png
  docs/assets/img/ulm_cards/card_cover_controls.png
  docs/assets/img/ulm_cards/card_cover_horizontal.png
  docs/usage/cards/card_cover.md
  docs/usage/cards/card_cover_buttons.md
Labels: :sparkles: enhancement

#534 [popup_card_light] add color to slider
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
Labels: :sparkles: enhancement

#536 fix: fix green on template with background-color and legacy variable
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/colors/green_on.yaml
Labels: :bug: bug

#531 Update Polish translation
  custom_cards/custom_card_eraycetinay_elapsed_time/languages/pl.yaml
  custom_cards/custom_card_eraycetinay_lock/languages/pl.yaml
  custom_cards/custom_card_imswel_person/languages/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/translations/pl.json
Labels: :speech_balloon: translation

#474 Minimalist iOS theme with tapbar
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-ios-tapbar/minimalist-ios-tapbar.yaml
Labels: :bulb: feature

#538 Update card_welcome_scenes.md
  docs/usage/cards/card_welcome_scenes.md
Labels: :memo: documentation

#502 [card_title] Bugfix rounded borders
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/title/card_title.yaml
Labels: :bug: bug

#537 [card_welcome_scenes] Bugfixes
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_weather_date.yaml
Labels: :bug: bug

#516 Create CONTRIBUTING.md
  .github/CONTRIBUTING.md
  README.md
Labels: :memo: documentation

#527 [card_vacuum] Bugfixes and add mopping
  custom_components/ui_lovelace_minimalist/lovelace/translations/cs.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/da.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/es.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/fr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/it.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/nl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/no.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pl.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/pt.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/sk.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/tr.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_vacuum.yaml
Labels: :bug: bug, :sparkles: enhancement

#548 custom_card_apexcharts
  custom_cards/custom_card_apexcharts/README.md
  custom_cards/custom_card_apexcharts/apexcharts.yaml
  docs/assets/img/custom_card_apexcharts_donut.png
  docs/assets/img/custom_card_apexcharts_line.png
  docs/assets/img/custom_card_apexcharts_radialBar.png
Labels: :sparkles: enhancement
