Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-05, with the labels that each got.

#1293 Frontend Fix Themes
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-ios-tapbar/minimalist-ios-tapbar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
  custom_components/ui_lovelace_minimalist/lovelace/themefiles/minimalist-mobile/minimalist-mobile.yaml
  hacs.json
Labels: :bug: bug

#1284 [custom_template_shogun160_battery_info] fix visablity when force_bac…
  custom_cards/custom_template_shogun160_battery_info/custom_template_shogun160_battery_info.yaml
Labels: :bug: bug

#1281 Added an extra variable that defines the stop stage of a washer/dryer…
  custom_cards/custom_card_haven_washer/README.md
  custom_cards/custom_card_haven_washer/custom_card_haven_washer.yaml
  docs/assets/img/custom_card_haven_washer_running.png
Labels: :sparkles: custom enhancement

#1287 Add ability to call script with custom fields/service_data to scene pills
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  docs/usage/cards/card_welcome_scenes.md
Labels: :sparkles: enhancement

#1292 Update README.md for Custom Chip Group Counter
  custom_cards/custom_chip_group_counter/README.md
Labels: :memo: documentation

#1295 Updated installation-docs
  custom_cards/custom_card_device_tracker/README.md
  custom_cards/custom_card_heat_pump/README.md
  docs/assets/img/Heat_pump.PNG
  docs/assets/img/heat_pump.gif
  docs/assets/img/setup/hacs_integration_config.png
  docs/setup/custom_cards.md
  docs/setup/installation.md
  docs/usage/custom_cards/custom_card_device_tracker.md
  docs/usage/custom_cards/custom_card_heat_pump.md
Labels: :memo: documentation
