Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-02, with the labels that each got.

#1098 Update Russian translation
  custom_cards/custom_card_camera/README.md
  custom_cards/custom_card_eraycetinay_lock/custom_card_eraycetinay_lock.yaml
  custom_cards/custom_card_esh_room/README.md
  custom_cards/custom_card_esh_room/custom_card_esh_room.yaml
  custom_cards/custom_card_irmajavi_speedtest/languages/de.yaml
  custom_components/ui_lovelace_minimalist/lovelace/translations/ru.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/chips/chip_mdi_icon_state.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_layouts/popup_light_effect_row.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
  custom_components/ui_lovelace_minimalist/translations/ru.json
  docs/troubleshooting/troubleshooting.md
  docs/usage/cards/card_light.md
  docs/usage/custom_cards/custom_card_camera.md
  docs/usage/custom_cards/custom_card_esh_room.md
  docs/usage/custom_cards/custom_card_imswel_person.md
  docs/usage/popups/popup_light.md
Labels: :speech_balloon: translation

#1124 Improve card_graph: Add line_width property
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_graph.yaml
  docs/usage/cards/card_graph.md
Labels: :sparkles: enhancement

#1176 feat: Relative time support for timestamp
  custom_components/ui_lovelace_minimalist/lovelace/translations/default.yaml
Labels: :bulb: feature

#1177 Fix: Mobile Popups
  custom_cards/custom_card_imswel_person/custom_card_imswel_person.yaml
  custom_cards/custom_card_schumijo_car/custom_card_schumijo_car.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_card.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_icon.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_light_more_options.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_button_source.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_brightness.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_color_temp.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_effect.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_light_palette.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_infos.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_source.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_media_player_volume.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_history.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_power_outlet_stats.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_radar.yaml
Labels: :bug: bug

#1175 Add swedish config flow
  custom_components/ui_lovelace_minimalist/translations/sv.json
  docs/usage/custom_cards/custom_card_paddy_waste_collection.md
Labels: :speech_balloon: translation

#1166 Added variable to set a custom temperature step in 'card_thermostat'.
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_thermostat.yaml
  docs/usage/cards/card_thermostat.md
Labels: :sparkles: enhancement

#1178 Fix: Multiple Bugs
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_scenes_welcome.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_thermostat_temperature.yaml
Labels: :bug: bug
