Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-06, with the labels that each got.

#1304 Fix timestamp bug
  custom_components/ui_lovelace_minimalist/lovelace/translations/default.yaml
Labels: :bug: bug

#1314 Add display precision based on HA settings
  custom_components/ui_lovelace_minimalist/lovelace/translations/default.yaml
Labels: :bulb: feature

#1324 Docs: Setup: reformat dependency list
  docs/setup/download.md
Labels: :memo: documentation
