Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-11, with the labels that each got.

#1378 Update sk.json
  custom_components/ui_lovelace_minimalist/translations/sk.json
Labels: :speech_balloon: translation

#1388 Fix Typo in troubleshooting.md
  docs/troubleshooting/troubleshooting.md
Labels: :memo: documentation

#1407 Fix #1406
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_binary_sensor_alert.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  docs/usage/cards/card_binary_sensor.md
  docs/usage/cards/card_binary_sensor_alert.md
Labels: :bug: bug

#1412 Update README.md
  .github/ISSUE_TEMPLATE/bug_report.md
  custom_cards/custom_card_input_datetime/README.md
Labels: :memo: documentation

#1415 Fix button service in scenes card
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
Labels: :bug: bug
