Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-03, with the labels that each got.

#1200 Custom Card Speedtest with ApexChart
  custom_cards/custom_card_speedtest_shogun160/custom_card_speedtest_shogun160.yaml
  custom_cards/custom_card_speedtest_shogun160/readme.md
  custom_components/ui_lovelace_minimalist/manifest.json
Labels: :bulb: custom feature

#1204 Card Cover Custom Colors
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_cover.yaml
  docs/usage/cards/card_cover.md
Labels: :sparkles: enhancement

#1205 Light Card Brightness Preset Buttons
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  docs/usage/cards/card_light.md
Labels: :sparkles: enhancement

#1206 Popup volume float fix
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popup_buttons/popup_chip_volume.yaml
Labels: :bug: bug

#1207 Update weather popup marker and color mode
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
Labels: :bug: bug, :sparkles: enhancement

#1203 Custom Chip "Garage"
  custom_cards/custom_chip_vlape_garage/README.md
  custom_cards/custom_chip_vlape_garage/custom_chip_vlape_garage.yaml
  docs/assets/img/custom_chip_vlape_garage/custom_chip_vlape_garage_dark.png
  docs/assets/img/custom_chip_vlape_garage/custom_chip_vlape_garage_light.png
Labels: :bulb: custom feature

#1197 Add custom chip group counter
  custom_cards/custom_chip_group_counter/README.md
  custom_cards/custom_chip_group_counter/custom_chip_group_counter.yaml
  custom_cards/custom_chip_group_counter/languages/en.yaml
  custom_cards/custom_chip_group_counter/languages/sv.yaml
  docs/assets/img/custom_card_group_counter_chip_dark.png
  docs/assets/img/custom_card_group_counter_chip_light.png
Labels: :bulb: custom feature

#1213 [card_weather] - use entity temperature when ulm_card_weather_custom isn't set
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_weather.yaml
Labels: :bug: bug

#1209 Card_light Rework color background
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_light.yaml
  docs/usage/cards/card_light.md
Labels: :sparkles: enhancement
