Repository UI-Lovelace-Minimalist/UI, pull requests merged in 2023-07, with the labels that each got.

#1330 Add Catalonian Language
  custom_components/ui_lovelace_minimalist/translations/ca.json
Labels: :speech_balloon: translation

#1344 Add shadow to chips in dark mode
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/chips.yaml
Labels: :sparkles: enhancement

#1341 Fix wrong variable referenced for service data for name hold action
  custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/actions/actions_name.yaml
Labels: :bug: bug
